### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#11]
This is not urgent, but it's another thing that is easier to start sooner than later. I found it helpful to poke around the `_pkgdown.yml` of other tidyverse packages that have gone before you. The pkgdown site for pkgdown itself 🤓 also has good basic info.

### pkgdown

  * [x] Add template `_pkgdown.yml`

```yaml
template:
  package: tidytemplate
  default_assets: false
```

  * [x] Add to `.Rbuildignore`

  * [x] `build_site()` then push.

  * [x] In admin use `docs/` for documentation and turn off wiki

  * [x] Update url on github repo page.

  * [x] Add url to DESCRIPTION.
